In [ ]:
import pandas as pd
from pathlib import Path

# Load cleaned dataset
data_path = Path("data/clean/expenses_main-clp_clean.csv")
df = pd.read_csv(data_path)

# Convert date to datetime
df["date"] = pd.to_datetime(df["date"])

# Print head of dataframe
print(f"DataFrame shape: {df.shape[0]} rows, {df.shape[1]} columns")
print(f"\nFirst few rows:")
df.sample(12)

DataFrame shape: 668 rows, 9 columns

First few rows:

,date,wallet,type,category,amount,currency,note,labels,budget
305,2025-05-12 18:35:53+00:00,Main CLP 🇨🇱,Expense,Groceries,1844.0,CLP,NaN,NaN,Gastos fijos
339,2025-05-27 23:15:25+00:00,Main CLP 🇨🇱,Expense,Snacks & Coffee,9020.0,CLP,NaN,NaN,Chao culpa
556,2025-10-12 15:47:50+00:00,Main CLP 🇨🇱,Expense,Groceries,10837.0,CLP,NaN,NaN,Gastos fijos
544,2025-10-04 22:23:47+00:00,Main CLP 🇨🇱,Expense,Shopping,17394.0,CLP,Afeitadora Philip,NaN,Chao culpa
557,2025-10-12 19:05:55+00:00,Main CLP 🇨🇱,Expense,Activities,12800.0,CLP,irok wall,NaN,Chao culpa
264,2025-04-23 15:09:44+00:00,Main CLP 🇨🇱,Expense,Subscriptions,790.0,CLP,Apple icloud plus 50 gb,NaN,Gastos fijos
450,2025-07-18 17:53:34+00:00,Main CLP 🇨🇱,Expense,Shopping,30000.0,CLP,Foto libro atlas de ale olivares,books,Chao culpa
387,2025-06-07 22:09:37+00:00,Main CLP 🇨🇱,Expense,Gifts,22865.0,CLP,Baby shower dieter,NaN,Chao culpa
552,2025-10-10 15:36:27+00:00,Main CLP 🇨🇱,Expense,Restaurant,10132.0,CLP,holy moly,NaN,Chao culpa
492,2025-09-03 20:46:53+00:00,Main CLP 🇨🇱,Expense,Snacks & Coffee,3380.0,CLP,NaN,NaN,Chao culpa
574,2025-10-24 19:47:21+00:00,Main CLP 🇨🇱,Expense,Snacks & Coffee,4500.0,CLP,Croissant,NaN,Chao culpa
497,2025-09-05 17:49:44+00:00,Main CLP 🇨🇱,Expense,Healthcare,15000.0,CLP,NaN,terapia,Gastos fijos

In [4]:
df.info()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 668 entries, 0 to 667
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      668 non-null    datetime64[ns, UTC]
 1   wallet    668 non-null    object
 2   type      668 non-null    object
 3   category  668 non-null    object
 4   amount    668 non-null    float64
 5   currency  668 non-null    object
 6   note      322 non-null    object
 7   labels    208 non-null    object
 8   budget    668 non-null    object
dtypes: datetime64[ns, UTC](1), float64(1), object(7)
memory usage: 47.1+ KB

             amount
count  6.680000e+02
mean   2.709574e+04
std    9.457762e+04
min    1.000000e+00
25%    4.073000e+03
50%    8.800000e+03
75%    1.900000e+04
max    1.640000e+06